### ISSUE TITLE
Bote fails to connect I2P Android

### ISSUE THREAD

**Issue by furyalex** [i2p/i2p.i2p-bote.android#4]
I installed latest versions of Bote and I2P router from Google play.

Router seems to be working. I can browse .i2p sites in Firefox. But when I press "connect to network" button in Bote it fails with

net.i2p.client.I2PSessionException: [I2P-Bote]: Cannot connect to the router on [Domain socket connection]:0
    at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:559)
    at i2p.bote.I2PBote.initializeSession(I2PBote.java:296)
    at i2p.bote.I2PBote.access$600(I2PBote.java:129)
    at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:971)
Caused by:

java.io.IOException: Connection refused
    at android.net.LocalSocketImpl.connectLocal(Native Method)
    at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:290)
    at android.net.LocalSocket.connect(LocalSocket.java:130)
    at net.i2p.client.DomainSocket.<init>(DomainSocket.java:34)
    at net.i2p.client.DomainSocketFactory.createSocket(DomainSocketFactory.java:24)
    at net.i2p.client.I2PSessionImpl.connect(I2PSessionImpl.java:491)
    at i2p.bote.I2PBote.initializeSession(I2PBote.java:296)
    at i2p.bote.I2PBote.access$600(I2PBote.java:129)
    at i2p.bote.I2PBote$ConnectTask.run(I2PBote.java:971)

Could you please suggest how I can resolve this.

I'm on Android 6.0.1 from AT&T. G890AUCS4CPF3

**Comment by Orbixx** [comment]
Experience the same.

**Comment by str4d** [comment]
I have migrated this issue to https://github.com/i2p/i2p.i2p-bote/issues/91.
